# Sử dụng Node.js image chính thức
FROM node:18.20.5-alpine3.21

# Đặt thư mục làm việc trong container
WORKDIR /app

# Sao chép file index.js vào trong container
COPY index.js .

# Chạy ứng dụng Node.js
CMD ["node", "index.js"]
